
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: May  5 2025 16:26:43 +07 (May  5 2025 09:26:43 UTC)

// Verification Directory fv/hazard_detection_unit 

module hazard_detection_unit(prev_opcode, curr_opcode, stall);
  input [2:0] prev_opcode, curr_opcode;
  output stall;
  wire [2:0] prev_opcode, curr_opcode;
  wire stall;
  wire n_0, n_1, n_2;
  AND4X1 g111__2398(.A (prev_opcode[2]), .B (prev_opcode[0]), .C (n_0),
       .D (n_2), .Y (stall));
  MXI2X1 g112__5107(.A (n_1), .B (curr_opcode[2]), .S0
       (curr_opcode[1]), .Y (n_2));
  NAND2BX1 g113__6260(.AN (curr_opcode[0]), .B (curr_opcode[2]), .Y
       (n_1));
  INVXL g114(.A (prev_opcode[1]), .Y (n_0));
endmodule

