
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: May  5 2025 17:12:43 +07 (May  5 2025 10:12:43 UTC)

// Verification Directory fv/address_mux 

module address_mux(pc_addr, instr_addr, sel, addr_out);
  input [4:0] pc_addr, instr_addr;
  input sel;
  output [4:0] addr_out;
  wire [4:0] pc_addr, instr_addr;
  wire sel;
  wire [4:0] addr_out;
  MX2X1 g131__2398(.A (instr_addr[4]), .B (pc_addr[4]), .S0 (sel), .Y
       (addr_out[4]));
  MX2X1 g135__5107(.A (instr_addr[2]), .B (pc_addr[2]), .S0 (sel), .Y
       (addr_out[2]));
  MX2X1 g132__6260(.A (instr_addr[1]), .B (pc_addr[1]), .S0 (sel), .Y
       (addr_out[1]));
  MX2X1 g133__4319(.A (instr_addr[0]), .B (pc_addr[0]), .S0 (sel), .Y
       (addr_out[0]));
  MX2X1 g134__8428(.A (instr_addr[3]), .B (pc_addr[3]), .S0 (sel), .Y
       (addr_out[3]));
endmodule

