
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: May  5 2025 17:11:53 +07 (May  5 2025 10:11:53 UTC)

// Verification Directory fv/accumulator 

module accumulator(clk, reset, load, data_in, acc_out);
  input clk, reset, load;
  input [7:0] data_in;
  output [7:0] acc_out;
  wire clk, reset, load;
  wire [7:0] data_in;
  wire [7:0] acc_out;
  wire n_0;
  SDFFRHQX1 \acc_out_reg[6] (.RN (n_0), .CK (clk), .D (acc_out[6]), .SI
       (data_in[6]), .SE (load), .Q (acc_out[6]));
  SDFFRHQX1 \acc_out_reg[4] (.RN (n_0), .CK (clk), .D (acc_out[4]), .SI
       (data_in[4]), .SE (load), .Q (acc_out[4]));
  SDFFRHQX1 \acc_out_reg[3] (.RN (n_0), .CK (clk), .D (acc_out[3]), .SI
       (data_in[3]), .SE (load), .Q (acc_out[3]));
  SDFFRHQX1 \acc_out_reg[1] (.RN (n_0), .CK (clk), .D (acc_out[1]), .SI
       (data_in[1]), .SE (load), .Q (acc_out[1]));
  SDFFRHQX1 \acc_out_reg[2] (.RN (n_0), .CK (clk), .D (acc_out[2]), .SI
       (data_in[2]), .SE (load), .Q (acc_out[2]));
  SDFFRHQX1 \acc_out_reg[7] (.RN (n_0), .CK (clk), .D (acc_out[7]), .SI
       (data_in[7]), .SE (load), .Q (acc_out[7]));
  SDFFRHQX1 \acc_out_reg[5] (.RN (n_0), .CK (clk), .D (acc_out[5]), .SI
       (data_in[5]), .SE (load), .Q (acc_out[5]));
  SDFFRHQX1 \acc_out_reg[0] (.RN (n_0), .CK (clk), .D (acc_out[0]), .SI
       (data_in[0]), .SE (load), .Q (acc_out[0]));
  INVXL g19(.A (reset), .Y (n_0));
endmodule

