
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: May  5 2025 17:23:11 +07 (May  5 2025 10:23:11 UTC)

// Verification Directory fv/instruction_register 

module instruction_register(clk, reset, load, data_in, instr_out);
  input clk, reset, load;
  input [7:0] data_in;
  output [7:0] instr_out;
  wire clk, reset, load;
  wire [7:0] data_in;
  wire [7:0] instr_out;
  wire n_0;
  SDFFRHQX1 \instr_out_reg[6] (.RN (n_0), .CK (clk), .D (instr_out[6]),
       .SI (data_in[6]), .SE (load), .Q (instr_out[6]));
  SDFFRHQX1 \instr_out_reg[4] (.RN (n_0), .CK (clk), .D (instr_out[4]),
       .SI (data_in[4]), .SE (load), .Q (instr_out[4]));
  SDFFRHQX1 \instr_out_reg[3] (.RN (n_0), .CK (clk), .D (instr_out[3]),
       .SI (data_in[3]), .SE (load), .Q (instr_out[3]));
  SDFFRHQX1 \instr_out_reg[1] (.RN (n_0), .CK (clk), .D (instr_out[1]),
       .SI (data_in[1]), .SE (load), .Q (instr_out[1]));
  SDFFRHQX1 \instr_out_reg[2] (.RN (n_0), .CK (clk), .D (instr_out[2]),
       .SI (data_in[2]), .SE (load), .Q (instr_out[2]));
  SDFFRHQX1 \instr_out_reg[7] (.RN (n_0), .CK (clk), .D (instr_out[7]),
       .SI (data_in[7]), .SE (load), .Q (instr_out[7]));
  SDFFRHQX1 \instr_out_reg[5] (.RN (n_0), .CK (clk), .D (instr_out[5]),
       .SI (data_in[5]), .SE (load), .Q (instr_out[5]));
  SDFFRHQX1 \instr_out_reg[0] (.RN (n_0), .CK (clk), .D (instr_out[0]),
       .SI (data_in[0]), .SE (load), .Q (instr_out[0]));
  INVXL g19(.A (reset), .Y (n_0));
endmodule

