
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: May  5 2025 17:28:26 +07 (May  5 2025 10:28:26 UTC)

// Verification Directory fv/program_counter 

module program_counter(clk, reset, load, inc, data_in, pc_out);
  input clk, reset, load, inc;
  input [4:0] data_in;
  output [4:0] pc_out;
  wire clk, reset, load, inc;
  wire [4:0] data_in;
  wire [4:0] pc_out;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_19, n_20, n_21, n_22, n_42, n_43;
  DFFRHQX1 \pc_out_reg[1] (.RN (n_22), .CK (clk), .D (n_16), .Q
       (pc_out[1]));
  DFFRHQX1 \pc_out_reg[3] (.RN (n_22), .CK (clk), .D (n_17), .Q
       (pc_out[3]));
  DFFRHQX1 \pc_out_reg[2] (.RN (n_22), .CK (clk), .D (n_20), .Q
       (pc_out[2]));
  DFFRX2 \pc_out_reg[0] (.RN (n_22), .CK (clk), .D (n_43), .Q
       (pc_out[0]), .QN (UNCONNECTED));
  DFFRHQX1 \pc_out_reg[4] (.RN (n_22), .CK (clk), .D (n_21), .Q
       (pc_out[4]));
  OAI2BB1X1 g489__2398(.A0N (pc_out[4]), .A1N (n_19), .B0 (n_15), .Y
       (n_21));
  OAI2BB1X1 g486__5107(.A0N (pc_out[2]), .A1N (n_19), .B0 (n_8), .Y
       (n_20));
  OAI2BB1X1 g487__4319(.A0N (pc_out[3]), .A1N (n_19), .B0 (n_11), .Y
       (n_17));
  OAI2BB1X1 g488__8428(.A0N (pc_out[1]), .A1N (n_19), .B0 (n_5), .Y
       (n_16));
  AND2X2 g491__5526(.A (n_0), .B (n_14), .Y (n_19));
  OAI2BB1X1 g493__3680(.A0N (pc_out[4]), .A1N (n_12), .B0 (inc), .Y
       (n_14));
  OA21X1 g494__1617(.A0 (pc_out[4]), .A1 (n_12), .B0 (n_10), .Y (n_13));
  AOI22X2 g495__2802(.A0 (n_9), .A1 (n_10), .B0 (load), .B1
       (data_in[3]), .Y (n_11));
  ADDHX1 g496__1705(.A (pc_out[3]), .B (n_6), .CO (n_12), .S (n_9));
  AOI22X2 g497__5122(.A0 (n_7), .A1 (n_10), .B0 (load), .B1
       (data_in[2]), .Y (n_8));
  ADDHX1 g498__8246(.A (pc_out[2]), .B (n_1), .CO (n_6), .S (n_7));
  AOI22X2 g499__7098(.A0 (n_2), .A1 (n_10), .B0 (load), .B1
       (data_in[1]), .Y (n_5));
  NOR2BX1 g502__1881(.AN (n_10), .B (pc_out[0]), .Y (n_3));
  ADDHX1 g500__5115(.A (pc_out[1]), .B (pc_out[0]), .CO (n_1), .S
       (n_2));
  AND2X2 g503__7482(.A (inc), .B (n_0), .Y (n_10));
  INVX1 g505(.A (load), .Y (n_0));
  INVXL g504(.A (reset), .Y (n_22));
  AO21X1 g2(.A0 (load), .A1 (data_in[0]), .B0 (n_3), .Y (n_42));
  AO21X1 g515(.A0 (pc_out[0]), .A1 (n_19), .B0 (n_42), .Y (n_43));
  AOI21X2 g492__517(.A0 (load), .A1 (data_in[4]), .B0 (n_13), .Y
       (n_15));
endmodule

